server:
    port: 8889
encrypt:
    key: ABCDEFGHAIJKLMNOPQRSTUVWYZ
spring:
    security:
        user:
            name: myuser
            password: mypassword
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/alvaroMaleno/spring-config-server-dev-values
                    search-paths:
                        - station*
                    repos:
                        perf:
                            pattern: '*/perf'
                            uri: https://github.com/alvaroMaleno/spring-config-server-values
                            search-paths:
                                - 'station*'
    